### ISSUE TITLE
CSS inline styles

### ISSUE THREAD

**Issue by ken-ani** [ken-kay/PSD-to-HTML#2]
Inline CSS styling in the HTML
#### Task(s)
- [ ] Move all the inline CSS styling from the HTML to the external style sheet.

**Comment by Tikkitai** [comment]
Is this still an issue? I attempted to look into it, but you had already moved the CSS to an external stylesheet. Also you should move the CSS styling into the CSS folder just to make it look neater.

**Comment by ken-ani** [comment]
> Is this still an issue? I attempted to look into it, but you had already moved the CSS to an external stylesheet. Also you should move the CSS styling into the CSS folder just to make it look neater.

Yes, it's a reminder for myself to go through the HTML removing all the inline styling so I have a cleaner file and everything else is moved to the CSS style sheet.

Ex: 
index.html - line 65
...`style="width: 100%; height: auto;" alt="hero">`
index.html - line 73
...`style="position:relative; top: -2rem; left:-3rem;"`

There are 10 instances of inline styling that I'll fix before closing this issue.

**Comment by ken-ani** [comment]
Shifting the styling to the stylesheet messes with the way it's displaying so I'll close this issue. 
The inline styling is working for the result since it overrides the external CSS file.
